# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'publish_dialog.ui'
#
# Created: Tue Jul 31 11:22:48 2012
#      by: PySide UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(793, 331)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 463, 25))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 771, 263))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid = QtGui.QGridLayout(self.gridLayoutWidget)
        self.grid.setObjectName("grid")
        self.controls = QtGui.QHBoxLayout()
        self.controls.setObjectName("controls")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.controls.addItem(spacerItem)
        self.cancel = QtGui.QPushButton(self.gridLayoutWidget)
        self.cancel.setObjectName("cancel")
        self.controls.addWidget(self.cancel)
        self.publish = QtGui.QPushButton(self.gridLayoutWidget)
        self.publish.setObjectName("publish")
        self.controls.addWidget(self.publish)
        self.grid.addLayout(self.controls, 1, 1, 1, 1)
        self.explorer = QtGui.QHBoxLayout()
        self.explorer.setObjectName("explorer")
        self.launcher = QtGui.QPushButton(self.gridLayoutWidget)
        self.launcher.setAutoFillBackground(False)
        self.launcher.setFlat(False)
        self.launcher.setObjectName("launcher")
        self.explorer.addWidget(self.launcher)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.explorer.addItem(spacerItem1)
        self.grid.addLayout(self.explorer, 1, 0, 1, 1)
        self.details = QtGui.QFrame(self.gridLayoutWidget)
        self.details.setFrameShape(QtGui.QFrame.StyledPanel)
        self.details.setFrameShadow(QtGui.QFrame.Sunken)
        self.details.setObjectName("details")
        self.formLayout = QtGui.QFormLayout(self.details)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.details)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.name = QtGui.QLineEdit(self.details)
        self.name.setMinimumSize(QtCore.QSize(350, 0))
        self.name.setObjectName("name")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.name)
        self.show = QtGui.QComboBox(self.details)
        self.show.setObjectName("show")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.show)
        self.sequence = QtGui.QComboBox(self.details)
        self.sequence.setObjectName("sequence")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.sequence)
        self.shot = QtGui.QComboBox(self.details)
        self.shot.setObjectName("shot")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.shot)
        self.label_4 = QtGui.QLabel(self.details)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.details)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.details)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.details)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.label_8 = QtGui.QLabel(self.details)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.tags = QtGui.QLineEdit(self.details)
        self.tags.setMinimumSize(QtCore.QSize(350, 0))
        self.tags.setObjectName("tags")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.tags)
        self.grid.addWidget(self.details, 0, 0, 1, 1)
        self.comments = QtGui.QFrame(self.gridLayoutWidget)
        self.comments.setFrameShape(QtGui.QFrame.StyledPanel)
        self.comments.setFrameShadow(QtGui.QFrame.Sunken)
        self.comments.setObjectName("comments")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.comments)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.c_label = QtGui.QLabel(self.comments)
        self.c_label.setObjectName("c_label")
        self.verticalLayout_2.addWidget(self.c_label)
        spacerItem3 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.comments_text = QtGui.QPlainTextEdit(self.comments)
        self.comments_text.setObjectName("comments_text")
        self.verticalLayout_2.addWidget(self.comments_text)
        self.grid.addWidget(self.comments, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.cancel, QtCore.SIGNAL("clicked()"), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "<b><big>Where would you like to publish this template to?</big></b>", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.publish.setText(QtGui.QApplication.translate("Dialog", "Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.launcher.setText(QtGui.QApplication.translate("Dialog", "Select Existing Release", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Publish Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "<b>Details</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.c_label.setText(QtGui.QApplication.translate("Dialog", "<b>Comments</b>", None, QtGui.QApplication.UnicodeUTF8))

